# Generated by Django 5.0.6 on 2024-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0002_remove_taskcategory_taskmodel'),
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='taskmodel',
            field=models.ManyToManyField(to='TaskCategory.taskcategory'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_assign_date',
            field=models.DateTimeField(),
        ),
    ]
